# Generated by Django 4.1 on 2025-05-24 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('year_of_experience', models.IntegerField()),
                ('phone_no', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('fee', models.CharField(default='1000', max_length=10)),
                ('time', models.CharField(default='00:00', max_length=10)),
                ('password', models.CharField(default='0000', max_length=10, null=True)),
                ('added_at', models.DateField(default=datetime.datetime.now)),
                ('specialty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='doctor.specialty')),
            ],
        ),
    ]
